version: 2.1
jobs:
  build:
    docker:
      - image: rocker/verse:3.5.3
    steps:
      - checkout
      - run: R --version
      - run: |
          R 
          devtools::load_all()
          devtools::install()
          library("dipl")
 