version: 2.1
jobs:
  build:
    docker:
      - image: 'r-base'
    steps:
      - checkout
      - run: R --version
      - run: |
          R -e "install.packages("devtools")"
          R -e "install.packages("roxygen2")"
 