version: 2.1
jobs:
  build:
    docker:
      - image: 'r-base'
    steps:
      - checkout
      - run: R --version
      - run: |
          R install.packages("devtools")
          R install.packages("roxygen2")
 