version: 2.1
jobs:
  build:
    docker:
      - image: thomaschln/r-devtools
    steps:
      - checkout
      - run: R --version
      - run: R -e 'install.packages("hms")'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
  
  test: 
    docker:
        - image: thomaschln/r-devtools
    steps:
      - checkout
      - run: R --version
      - run: R -e 'install.packages("hms")'
      - run:
          name: load functions
          command: R -e "devtools::load_all()"
      - run: |
          # cd ..
          # ls
          # Testen
          R -e "devtools::test()"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
 